site:
  title: "Aperture Lab"
  baseline: "Solutions numériques pragmatiques"
  baseurl: https://aperturelab.io/
  description: "Aperture Lab, Solutions numériques pragmatiques."
  language: fr
  author:
    name: "Arnaud Ligny"
    website: https://arnaudligny.fr
  about:
    url: https://arnaudligny.fr
